theme                    : jekyll-theme-minimal
locale                   : "en-US"
title                    : "Epochalypse Project"
title_separator          : "-"
name                     : "Epochalypse Project"
description              : "Raising awareness about the 2038 bug in all its manifestations and trying to fix things while there's still time."
show_links               : true
logo                     : assets/images/punk-sloth.png
discussion_url           : https://github.com/orgs/Epochalypse-Project/discussions
faq_url                  : https://github.com/Epochalypse-Project/hive/wiki/faq
wiki_url                 : https://github.com/Epochalypse-Project/hive/wiki
github:
  is_project_page        : false
  is_user_page           : false
  owner_url              : https://epochalypse-project.org/
